name: mobile
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^0.13.1
  cupertino_icons: ^1.0.2
  fl_chart: ^0.63.0
  d_chart: ^2.3.0
  google_maps_flutter: ^2.3.1
  latlong2: ^0.8.2
  json_annotation: ^4.8.1
  logger: ^2.0.1
  flutter_dotenv: ^5.1.0
  http: ^0.13.6
  geolocator: ^9.0.2
  geocoding: ^2.0.0
  permission_handler: ^10.4.3
  google_maps_webservice: ^0.0.19
  flutter_polyline_points: ^1.0.0
  collection: ^1.17.1
  flutter_background_service: ^3.0.1
  flutter_background_service_android: ^4.0.1
  light: ^3.0.1
  battery_plus: ^4.0.1
  sensors_plus: ^3.0.2
  firebase_core: ^2.15.1
  cloud_firestore: ^4.8.3
  shared_preferences: ^2.2.0
  sqflite: ^2.2.8+4
  path: ^1.8.3
  path_provider: ^2.0.15
  intl: ^0.17.0
  flutter_svg: ^0.22.0
  timeline_tile: ^2.0.0
  camera:
  tflite_flutter:
  tflite_v2: ^1.0.0
  flutter_slidable: ^0.6.0
  audioplayers: ^5.2.0
  flutter_survey: ^0.1.4

#  is_screen_locked:
#    path: ../flutter_packages/is_screen_locked
  convert: ^3.1.1
  firebase_auth: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  json_serializable: ^6.7.1

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/sleep_quality/
    - assets/emotion_prediction/
    - assets/emotion_prediction/model_unquant.tflite
    - assets/emotion_prediction/labels.txt
    - assets/common/
    - assets/audios/
    - .env
    - .env.production
    - .env.development

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
