// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-P-JW4mx__80qdHVgmF46JPbAbFcSizY',
    appId: '1:729400734743:web:ec27e290a3e7e5f1c51852',
    messagingSenderId: '729400734743',
    projectId: 'daily-pulse-8c8c5',
    authDomain: 'daily-pulse-8c8c5.firebaseapp.com',
    databaseURL: 'https://daily-pulse-8c8c5-default-rtdb.firebaseio.com',
    storageBucket: 'daily-pulse-8c8c5.appspot.com',
    measurementId: 'G-QXMQZBTVBG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDR8LzAVybx7FU6pMHY8bXKFuQK5-c2mV4',
    appId: '1:729400734743:android:15df96bf49bbe2bdc51852',
    messagingSenderId: '729400734743',
    projectId: 'daily-pulse-8c8c5',
    databaseURL: 'https://daily-pulse-8c8c5-default-rtdb.firebaseio.com',
    storageBucket: 'daily-pulse-8c8c5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8TMmB9NiJg858mTUwY0DYyIk4qYVvfcU',
    appId: '1:729400734743:ios:2645b8e266ab85cac51852',
    messagingSenderId: '729400734743',
    projectId: 'daily-pulse-8c8c5',
    databaseURL: 'https://daily-pulse-8c8c5-default-rtdb.firebaseio.com',
    storageBucket: 'daily-pulse-8c8c5.appspot.com',
    iosClientId: '729400734743-7n7qg756cbjp5er306gtic97okfsafi1.apps.googleusercontent.com',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8TMmB9NiJg858mTUwY0DYyIk4qYVvfcU',
    appId: '1:729400734743:ios:fcb4261b3e2491a4c51852',
    messagingSenderId: '729400734743',
    projectId: 'daily-pulse-8c8c5',
    databaseURL: 'https://daily-pulse-8c8c5-default-rtdb.firebaseio.com',
    storageBucket: 'daily-pulse-8c8c5.appspot.com',
    iosClientId: '729400734743-uj719ra4idp8ja1vn087anuturpaa96c.apps.googleusercontent.com',
    iosBundleId: 'com.example.mobile.RunnerTests',
  );
}
